#include "sihopt/linalg/dense_lu.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>
namespace sihopt::linalg {
namespace {
constexpr std::size_t maximum_dense_elements = 4U * 1024U * 1024U;
std::size_t checked_product(std::size_t a,std::size_t b){if(a!=0U&&b>std::numeric_limits<std::size_t>::max()/a)throw std::length_error("dense matrix size overflow");const auto n=a*b;if(n>maximum_dense_elements)throw std::length_error("dense oracle element limit exceeded");return n;}
void finite(double v,const char* message){if(!std::isfinite(v))throw std::overflow_error(message);}
}
double& DenseMatrix::operator()(std::size_t r,std::size_t c){if(r>=rows||c>=columns)throw std::out_of_range("dense matrix index");const auto n=checked_product(rows,columns);if(values.size()!=n)throw std::invalid_argument("dense matrix dimension mismatch");return values.at(r*columns+c);}
double DenseMatrix::operator()(std::size_t r,std::size_t c)const{if(r>=rows||c>=columns)throw std::out_of_range("dense matrix index");const auto n=checked_product(rows,columns);if(values.size()!=n)throw std::invalid_argument("dense matrix dimension mismatch");return values.at(r*columns+c);}
void DenseMatrix::validate()const{if(values.size()!=checked_product(rows,columns))throw std::invalid_argument("dense matrix dimension mismatch");for(double v:values)if(!std::isfinite(v))throw std::invalid_argument("dense matrix contains non-finite value");}
DenseLu DenseLu::factorize(const DenseMatrix& a,double tol){a.validate();if(a.rows!=a.columns)throw std::invalid_argument("dense LU requires square matrix");if(!std::isfinite(tol)||tol<0)throw std::invalid_argument("invalid singular tolerance");DenseLu f;f.dimension_=a.rows;f.lu_=a.values;f.pivots_.resize(a.rows);for(double v:a.values)f.diagnostics_.maximum_original_entry=std::max(f.diagnostics_.maximum_original_entry,std::abs(v));f.diagnostics_.minimum_absolute_pivot=std::numeric_limits<double>::infinity();
for(std::size_t k=0;k<a.rows;++k){std::size_t p=k;double best=std::abs(f.lu_[k*a.rows+k]);for(std::size_t i=k+1;i<a.rows;++i){const double q=std::abs(f.lu_[i*a.rows+k]);if(q>best){best=q;p=i;}}const double scale=std::max(1.0,f.diagnostics_.maximum_original_entry);if(best<=tol*scale)throw std::runtime_error("singular or near-singular matrix");f.pivots_[k]=p;if(p!=k)for(std::size_t j=0;j<a.rows;++j)std::swap(f.lu_[k*a.rows+j],f.lu_[p*a.rows+j]);const double pivot=f.lu_[k*a.rows+k];f.diagnostics_.minimum_absolute_pivot=std::min(f.diagnostics_.minimum_absolute_pivot,std::abs(pivot));f.diagnostics_.maximum_absolute_pivot=std::max(f.diagnostics_.maximum_absolute_pivot,std::abs(pivot));for(std::size_t i=k+1;i<a.rows;++i){f.lu_[i*a.rows+k]/=pivot;finite(f.lu_[i*a.rows+k],"non-finite LU multiplier");const double m=f.lu_[i*a.rows+k];for(std::size_t j=k+1;j<a.rows;++j){f.lu_[i*a.rows+j]-=m*f.lu_[k*a.rows+j];finite(f.lu_[i*a.rows+j],"non-finite LU update");}}}
if(a.rows==0){f.diagnostics_.minimum_absolute_pivot=0;} f.diagnostics_.pivot_ratio=f.diagnostics_.maximum_absolute_pivot==0?0:f.diagnostics_.minimum_absolute_pivot/f.diagnostics_.maximum_absolute_pivot;return f;}
std::vector<double> DenseLu::solve(const std::vector<double>& b)const{if(b.size()!=dimension_)throw std::invalid_argument("rhs dimension mismatch");std::vector<double>x=b;for(double v:x)finite(v,"non-finite rhs");for(std::size_t k=0;k<dimension_;++k)if(pivots_[k]!=k)std::swap(x[k],x[pivots_[k]]);for(std::size_t k=0;k<dimension_;++k)for(std::size_t i=k+1;i<dimension_;++i){x[i]-=lu_[i*dimension_+k]*x[k];finite(x[i],"non-finite forward solve");}for(std::size_t k=dimension_;k-->0;){for(std::size_t j=k+1;j<dimension_;++j){x[k]-=lu_[k*dimension_+j]*x[j];finite(x[k],"non-finite back solve");}x[k]/=lu_[k*dimension_+k];finite(x[k],"non-finite solution");}return x;}
std::vector<double> DenseLu::solve_transpose(const std::vector<double>& b)const{if(b.size()!=dimension_)throw std::invalid_argument("rhs dimension mismatch");std::vector<double>x=b;for(double v:x)finite(v,"non-finite rhs");for(std::size_t k=0;k<dimension_;++k){for(std::size_t i=0;i<k;++i){x[k]-=lu_[i*dimension_+k]*x[i];finite(x[k],"non-finite transpose solve");}x[k]/=lu_[k*dimension_+k];finite(x[k],"non-finite transpose solution");}for(std::size_t k=dimension_;k-->0;)for(std::size_t i=k+1;i<dimension_;++i){x[k]-=lu_[i*dimension_+k]*x[i];finite(x[k],"non-finite transpose solve");}for(std::size_t k=dimension_;k-->0;)if(pivots_[k]!=k)std::swap(x[k],x[pivots_[k]]);return x;}
std::vector<double> multiply(const DenseMatrix&a,const std::vector<double>&x){a.validate();if(x.size()!=a.columns)throw std::invalid_argument("multiply dimension mismatch");for(double v:x)finite(v,"non-finite multiply operand");std::vector<double>y(a.rows);for(std::size_t i=0;i<a.rows;++i){long double s=0;for(std::size_t j=0;j<a.columns;++j)s+=static_cast<long double>(a(i,j))*x[j];y[i]=static_cast<double>(s);finite(y[i],"non-finite matrix product");}return y;}
std::vector<double> multiply_transpose(const DenseMatrix&a,const std::vector<double>&x){a.validate();if(x.size()!=a.rows)throw std::invalid_argument("transpose multiply dimension mismatch");for(double v:x)finite(v,"non-finite multiply operand");std::vector<double>y(a.columns);for(std::size_t j=0;j<a.columns;++j){long double s=0;for(std::size_t i=0;i<a.rows;++i)s+=static_cast<long double>(a(i,j))*x[i];y[j]=static_cast<double>(s);finite(y[j],"non-finite matrix product");}return y;}
double infinity_residual(const DenseMatrix&a,const std::vector<double>&x,const std::vector<double>&b,bool t){auto y=t?multiply_transpose(a,x):multiply(a,x);if(y.size()!=b.size())throw std::invalid_argument("residual dimension mismatch");double r=0;for(std::size_t i=0;i<y.size();++i){finite(b[i],"non-finite residual rhs");const double d=std::abs(y[i]-b[i]);finite(d,"non-finite residual");r=std::max(r,d);}return r;}
}
